extends:
  - "eslint:recommended"
  - "prettier"
parserOptions:
  ecmaVersion: 2018
overrides:
  - files:
      - "*.js"
    env:
      node: true

  - files:
      - "src/*.js"
    env:
      browser: true
